version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_URLBASE=postgresql://
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=trialfastapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=pgadmin
      - SECRET_KEY=JingalalaHo!
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=trialfastapi

    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5598:5432

volumes:
  db-postgres: